//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace ND.PolicyReceiveServiceSite.PolicyServiceBy19e {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SyncRateServiceGHImplServiceSoapBinding", Namespace="http://impl.service.iesales.speed.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(statusResponse))]
    public partial class SyncRateServiceGHImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSyncRateDelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSyncRateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SyncRateServiceGHImplService() {
            this.Url = global::ND.PolicyReceiveServiceSite.Properties.Settings.Default.ND_PolicyReceiveServiceSite_PolicyServiceBy19e_SyncRateServiceGHImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSyncRateDelCompletedEventHandler GetSyncRateDelCompleted;
        
        /// <remarks/>
        public event GetSyncRateCompletedEventHandler GetSyncRateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.iesales.speed.com/", ResponseNamespace="http://service.iesales.speed.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public syncRateDelResponse GetSyncRateDel([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] syncRateDelRequest arg0) {
            object[] results = this.Invoke("GetSyncRateDel", new object[] {
                        arg0});
            return ((syncRateDelResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetSyncRateDelAsync(syncRateDelRequest arg0) {
            this.GetSyncRateDelAsync(arg0, null);
        }
        
        /// <remarks/>
        public void GetSyncRateDelAsync(syncRateDelRequest arg0, object userState) {
            if ((this.GetSyncRateDelOperationCompleted == null)) {
                this.GetSyncRateDelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSyncRateDelOperationCompleted);
            }
            this.InvokeAsync("GetSyncRateDel", new object[] {
                        arg0}, this.GetSyncRateDelOperationCompleted, userState);
        }
        
        private void OnGetSyncRateDelOperationCompleted(object arg) {
            if ((this.GetSyncRateDelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSyncRateDelCompleted(this, new GetSyncRateDelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.iesales.speed.com/", ResponseNamespace="http://service.iesales.speed.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public syncRateResponse GetSyncRate([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] syncRateRequest arg0) {
            object[] results = this.Invoke("GetSyncRate", new object[] {
                        arg0});
            return ((syncRateResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetSyncRateAsync(syncRateRequest arg0) {
            this.GetSyncRateAsync(arg0, null);
        }
        
        /// <remarks/>
        public void GetSyncRateAsync(syncRateRequest arg0, object userState) {
            if ((this.GetSyncRateOperationCompleted == null)) {
                this.GetSyncRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSyncRateOperationCompleted);
            }
            this.InvokeAsync("GetSyncRate", new object[] {
                        arg0}, this.GetSyncRateOperationCompleted, userState);
        }
        
        private void OnGetSyncRateOperationCompleted(object arg) {
            if ((this.GetSyncRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSyncRateCompleted(this, new GetSyncRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.iesales.speed.com/")]
    public partial class syncRateDelRequest {
        
        private string appcodeField;
        
        private string deleteStrategyIdField;
        
        private string pageSizeField;
        
        private string signField;
        
        private string updateTimeField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appcode {
            get {
                return this.appcodeField;
            }
            set {
                this.appcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deleteStrategyId {
            get {
                return this.deleteStrategyIdField;
            }
            set {
                this.deleteStrategyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string updateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.iesales.speed.com/")]
    public partial class syncRateRequest {
        
        private string aircomp2cField;
        
        private string appcodeField;
        
        private string minDiscountField;
        
        private string pageSizeField;
        
        private string psgTypeField;
        
        private string rateTypeField;
        
        private string signField;
        
        private string strategyIdField;
        
        private string updateTimeField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aircomp2c {
            get {
                return this.aircomp2cField;
            }
            set {
                this.aircomp2cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appcode {
            get {
                return this.appcodeField;
            }
            set {
                this.appcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string minDiscount {
            get {
                return this.minDiscountField;
            }
            set {
                this.minDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psgType {
            get {
                return this.psgTypeField;
            }
            set {
                this.psgTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rateType {
            get {
                return this.rateTypeField;
            }
            set {
                this.rateTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strategyId {
            get {
                return this.strategyIdField;
            }
            set {
                this.strategyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string updateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.iesales.speed.com/")]
    public partial class rate {
        
        private string aircomp2cField;
        
        private decimal backrateField;
        
        private bool backrateFieldSpecified;
        
        private string chngretmemoField;
        
        private string daysFitField;
        
        private System.DateTime edateField;
        
        private bool edateFieldSpecified;
        
        private string flightclassField;
        
        private string flightnoFitField;
        
        private string flightnoNotFitField;
        
        private string fromport3cField;
        
        private timestamp opdateField;
        
        private string outagentidField;
        
        private int psgtypeField;
        
        private bool psgtypeFieldSpecified;
        
        private string ratetypeField;
        
        private decimal routetypeField;
        
        private bool routetypeFieldSpecified;
        
        private System.DateTime sdateField;
        
        private bool sdateFieldSpecified;
        
        private decimal stateField;
        
        private bool stateFieldSpecified;
        
        private decimal strategyIdField;
        
        private bool strategyIdFieldSpecified;
        
        private decimal strategyTypeField;
        
        private bool strategyTypeFieldSpecified;
        
        private string thespeedField;
        
        private string toport3cField;
        
        private int usertypeField;
        
        private bool usertypeFieldSpecified;
        
        private string voidtimeField;
        
        private string worktimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aircomp2c {
            get {
                return this.aircomp2cField;
            }
            set {
                this.aircomp2cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal backrate {
            get {
                return this.backrateField;
            }
            set {
                this.backrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool backrateSpecified {
            get {
                return this.backrateFieldSpecified;
            }
            set {
                this.backrateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string chngretmemo {
            get {
                return this.chngretmemoField;
            }
            set {
                this.chngretmemoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string daysFit {
            get {
                return this.daysFitField;
            }
            set {
                this.daysFitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime edate {
            get {
                return this.edateField;
            }
            set {
                this.edateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool edateSpecified {
            get {
                return this.edateFieldSpecified;
            }
            set {
                this.edateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flightclass {
            get {
                return this.flightclassField;
            }
            set {
                this.flightclassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flightnoFit {
            get {
                return this.flightnoFitField;
            }
            set {
                this.flightnoFitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flightnoNotFit {
            get {
                return this.flightnoNotFitField;
            }
            set {
                this.flightnoNotFitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fromport3c {
            get {
                return this.fromport3cField;
            }
            set {
                this.fromport3cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public timestamp opdate {
            get {
                return this.opdateField;
            }
            set {
                this.opdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string outagentid {
            get {
                return this.outagentidField;
            }
            set {
                this.outagentidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int psgtype {
            get {
                return this.psgtypeField;
            }
            set {
                this.psgtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool psgtypeSpecified {
            get {
                return this.psgtypeFieldSpecified;
            }
            set {
                this.psgtypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ratetype {
            get {
                return this.ratetypeField;
            }
            set {
                this.ratetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal routetype {
            get {
                return this.routetypeField;
            }
            set {
                this.routetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool routetypeSpecified {
            get {
                return this.routetypeFieldSpecified;
            }
            set {
                this.routetypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime sdate {
            get {
                return this.sdateField;
            }
            set {
                this.sdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sdateSpecified {
            get {
                return this.sdateFieldSpecified;
            }
            set {
                this.sdateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal strategyId {
            get {
                return this.strategyIdField;
            }
            set {
                this.strategyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strategyIdSpecified {
            get {
                return this.strategyIdFieldSpecified;
            }
            set {
                this.strategyIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal strategyType {
            get {
                return this.strategyTypeField;
            }
            set {
                this.strategyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strategyTypeSpecified {
            get {
                return this.strategyTypeFieldSpecified;
            }
            set {
                this.strategyTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string thespeed {
            get {
                return this.thespeedField;
            }
            set {
                this.thespeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string toport3c {
            get {
                return this.toport3cField;
            }
            set {
                this.toport3cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int usertype {
            get {
                return this.usertypeField;
            }
            set {
                this.usertypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usertypeSpecified {
            get {
                return this.usertypeFieldSpecified;
            }
            set {
                this.usertypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string voidtime {
            get {
                return this.voidtimeField;
            }
            set {
                this.voidtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string worktime {
            get {
                return this.worktimeField;
            }
            set {
                this.worktimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.iesales.speed.com/")]
    public partial class timestamp {
        
        private int nanosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nanos {
            get {
                return this.nanosField;
            }
            set {
                this.nanosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.iesales.speed.com/")]
    public partial class rateDel {
        
        private string deletestrategyidField;
        
        private timestamp opdateField;
        
        private decimal strategyIdField;
        
        private bool strategyIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deletestrategyid {
            get {
                return this.deletestrategyidField;
            }
            set {
                this.deletestrategyidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public timestamp opdate {
            get {
                return this.opdateField;
            }
            set {
                this.opdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal strategyId {
            get {
                return this.strategyIdField;
            }
            set {
                this.strategyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strategyIdSpecified {
            get {
                return this.strategyIdFieldSpecified;
            }
            set {
                this.strategyIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(syncRateResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(syncRateDelResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.iesales.speed.com/")]
    public partial class statusResponse {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.iesales.speed.com/")]
    public partial class syncRateResponse : statusResponse {
        
        private string lastStrategyIdField;
        
        private int pageCountField;
        
        private bool pageCountFieldSpecified;
        
        private rate[] rateListField;
        
        private string updateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastStrategyId {
            get {
                return this.lastStrategyIdField;
            }
            set {
                this.lastStrategyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageCountSpecified {
            get {
                return this.pageCountFieldSpecified;
            }
            set {
                this.pageCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rateList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public rate[] rateList {
            get {
                return this.rateListField;
            }
            set {
                this.rateListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string updateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.iesales.speed.com/")]
    public partial class syncRateDelResponse : statusResponse {
        
        private string deleteStrategyIdField;
        
        private rateDel[] rateListField;
        
        private string strategyIdField;
        
        private string updateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deleteStrategyId {
            get {
                return this.deleteStrategyIdField;
            }
            set {
                this.deleteStrategyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rateList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public rateDel[] rateList {
            get {
                return this.rateListField;
            }
            set {
                this.rateListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strategyId {
            get {
                return this.strategyIdField;
            }
            set {
                this.strategyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string updateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSyncRateDelCompletedEventHandler(object sender, GetSyncRateDelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSyncRateDelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSyncRateDelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public syncRateDelResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((syncRateDelResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSyncRateCompletedEventHandler(object sender, GetSyncRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSyncRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSyncRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public syncRateResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((syncRateResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591